// src/components/AI/cards/InvoiceResultCard.jsx
import { Download, Send, Pencil } from "lucide-react";

function formatCurrency(amount) {
    return `₹${amount.toLocaleString("en-IN")}`;
}

/**
 * `data` shape: { number, client, items: [{ name, qty, rate }], taxRate, dueDate }
 * Totals are derived from items here, same as InvoiceDetailPanel, so a card
 * generated by the AI can never show numbers that don't add up.
 */
export default function InvoiceResultCard({ data, onEdit, onSendToClient, onExportPdf }) {
    const subtotal = data.items.reduce((sum, item) => sum + item.qty * item.rate, 0);
    const tax = Math.round(subtotal * (data.taxRate / 100));
    const total = subtotal + tax;

    return (
        <div className="max-w-xl rounded-2xl border border-gray-100 bg-white p-4 shadow-sm">
            <div className="flex items-center justify-between">
                <h4 className="text-sm font-semibold text-gray-900">Invoice Generated — {data.number}</h4>
                <span className="rounded-full bg-emerald-100 px-2.5 py-0.5 text-xs font-medium text-emerald-700">Ready</span>
            </div>
            <p className="mt-1 text-xs text-gray-400">For {data.client} · Due {data.dueDate}</p>

            <table className="mt-3 w-full text-sm">
                <thead>
                    <tr className="text-left text-xs text-gray-400">
                        <th className="pb-1.5 font-medium">Item</th>
                        <th className="pb-1.5 text-right font-medium">Qty</th>
                        <th className="pb-1.5 text-right font-medium">Rate</th>
                        <th className="pb-1.5 text-right font-medium">Amount</th>
                    </tr>
                </thead>
                <tbody className="divide-y divide-gray-50">
                    {data.items.map((item) => (
                        <tr key={item.name}>
                            <td className="py-1.5 text-gray-700">{item.name}</td>
                            <td className="py-1.5 text-right text-gray-700">{item.qty}</td>
                            <td className="py-1.5 text-right text-gray-700">{formatCurrency(item.rate)}</td>
                            <td className="py-1.5 text-right font-medium text-gray-900">{formatCurrency(item.qty * item.rate)}</td>
                        </tr>
                    ))}
                </tbody>
            </table>

            <div className="mt-3 space-y-1 border-t border-gray-50 pt-2 text-sm">
                <div className="flex justify-between text-gray-500"><span>Subtotal</span><span>{formatCurrency(subtotal)}</span></div>
                <div className="flex justify-between text-gray-500"><span>Tax ({data.taxRate}%)</span><span>{formatCurrency(tax)}</span></div>
                <div className="flex justify-between font-semibold text-gray-900"><span>Total</span><span>{formatCurrency(total)}</span></div>
            </div>

            <div className="mt-4 flex flex-wrap gap-2">
                <button type="button" onClick={onEdit} className="flex items-center gap-1.5 rounded-lg border border-gray-200 px-3 py-1.5 text-xs font-medium text-gray-700 hover:bg-gray-50">
                    <Pencil size={13} /> Edit
                </button>
                <button type="button" onClick={onExportPdf} className="flex items-center gap-1.5 rounded-lg border border-gray-200 px-3 py-1.5 text-xs font-medium text-gray-700 hover:bg-gray-50">
                    <Download size={13} /> Export PDF
                </button>
                <button type="button" onClick={onSendToClient} className="ml-auto flex items-center gap-1.5 rounded-lg bg-violet-600 px-3 py-1.5 text-xs font-medium text-white hover:bg-violet-700">
                    <Send size={13} /> Send to Client
                </button>
            </div>
        </div>
    );
}