// src/components/AI/cards/MeetingNotesResultCard.jsx
import { Copy, Download } from "lucide-react";

/**
 * `data` shape: { title, date, time, attendees: [string], overview,
 * keyPoints: [string], decisions: [string],
 * actionItems: [{ task, owner, dueDate }], nextMeeting: { date, time, location } }
 */
export default function MeetingNotesResultCard({ data, onCopy, onExportPdf }) {
    return (
        <div className="max-w-2xl rounded-2xl border border-gray-100 bg-white p-4 shadow-sm">
            <div className="flex items-center justify-between">
                <div>
                    <h4 className="text-sm font-semibold text-gray-900">{data.title}</h4>
                    <p className="text-xs text-gray-400">
                        {data.date} · {data.time} · {data.attendees.join(", ")}
                    </p>
                </div>
                <div className="flex gap-2">
                    <button type="button" onClick={onCopy} className="flex items-center gap-1 rounded-lg border border-gray-200 px-2.5 py-1 text-xs font-medium text-gray-700 hover:bg-gray-50">
                        <Copy size={12} /> Copy
                    </button>
                    <button type="button" onClick={onExportPdf} className="flex items-center gap-1 rounded-lg border border-gray-200 px-2.5 py-1 text-xs font-medium text-gray-700 hover:bg-gray-50">
                        <Download size={12} /> Export PDF
                    </button>
                </div>
            </div>

            <div className="mt-3 grid grid-cols-1 gap-3 sm:grid-cols-2">
                <div className="rounded-xl bg-gray-50 p-3">
                    <p className="text-xs font-semibold text-violet-600">Meeting Overview</p>
                    <p className="mt-1 text-sm text-gray-600">{data.overview}</p>
                </div>
                <div className="rounded-xl bg-gray-50 p-3">
                    <p className="text-xs font-semibold text-violet-600">Key Discussion Points</p>
                    <ul className="mt-1 space-y-1 text-sm text-gray-700">
                        {data.keyPoints.map((point) => (
                            <li key={point}>• {point}</li>
                        ))}
                    </ul>
                </div>
                <div className="rounded-xl bg-gray-50 p-3">
                    <p className="text-xs font-semibold text-emerald-600">Decisions Made</p>
                    <ul className="mt-1 space-y-1 text-sm text-gray-700">
                        {data.decisions.map((point) => (
                            <li key={point} className="flex items-start gap-1.5">
                                <span className="text-emerald-500">✓</span> {point}
                            </li>
                        ))}
                    </ul>
                </div>
                <div className="rounded-xl bg-gray-50 p-3">
                    <p className="text-xs font-semibold text-orange-600">Next Meeting</p>
                    <p className="mt-1 text-sm text-gray-700">{data.nextMeeting.date}</p>
                    <p className="text-sm text-gray-500">{data.nextMeeting.time} · {data.nextMeeting.location}</p>
                </div>
            </div>

            <div className="mt-3 rounded-xl bg-gray-50 p-3">
                <p className="text-xs font-semibold text-gray-600">Action Items</p>
                <table className="mt-1.5 w-full text-sm">
                    <thead>
                        <tr className="text-left text-xs text-gray-400">
                            <th className="pb-1 font-medium">Task</th>
                            <th className="pb-1 font-medium">Owner</th>
                            <th className="pb-1 font-medium">Due Date</th>
                        </tr>
                    </thead>
                    <tbody className="divide-y divide-gray-100">
                        {data.actionItems.map((item) => (
                            <tr key={item.task}>
                                <td className="py-1 text-gray-700">{item.task}</td>
                                <td className="py-1 text-gray-700">{item.owner}</td>
                                <td className="py-1 text-gray-700">{item.dueDate}</td>
                            </tr>
                        ))}
                    </tbody>
                </table>
            </div>

            <p className="mt-3 text-xs text-gray-400">These notes were generated by AI. Please review and make any necessary edits.</p>
        </div>
    );
}