// src/services/pdfService.js
import PDFDocument from "pdfkit";

// ---------------------------------------------------------------------------
// Design tokens — kept in one place so all three PDF types stay visually
// consistent, and a future brand color change is a one-line edit.
// ---------------------------------------------------------------------------
const COLORS = {
  brand: "#7C3AED",
  brandDark: "#5B21B6",
  textDark: "#1F2937",
  textGray: "#6B7280",
  textLight: "#9CA3AF",
  border: "#E5E7EB",
  tableHeaderBg: "#F5F3FF",
  success: "#059669",
  warning: "#D97706",
  danger: "#DC2626",
};

const PAGE_MARGIN = 50;
const PAGE_WIDTH = 595.28; // A4 width in points

function formatCurrency(amount) {
  return `Rs. ${Number(amount || 0).toLocaleString("en-IN", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
}

function formatDate(date) {
  if (!date) return "-";
  return new Date(date).toLocaleDateString("en-US", { day: "2-digit", month: "short", year: "numeric" });
}

// ---------------------------------------------------------------------------
// Shared layout pieces — header, footer, page numbers. Every PDF type calls
// these so a design change (e.g. swapping the logo placeholder for a real
// image later) only needs to happen in one place.
// ---------------------------------------------------------------------------

/**
 * Draws the branded header: logo placeholder + company name/tagline, plus
 * the document title (e.g. "INVOICE", "PROPOSAL", "SERVICE AGREEMENT") on
 * the right side of the same row.
 */
function drawHeader(doc, documentTitle) {
  // Logo placeholder — a simple rounded square with an "F" mark. Swap for
  // doc.image(path, x, y, { width }) once a real logo file is available.
  doc.roundedRect(PAGE_MARGIN, 45, 36, 36, 8).fill(COLORS.brand);
  doc
    .fillColor("#FFFFFF")
    .font("Helvetica-Bold")
    .fontSize(18)
    .text("F", PAGE_MARGIN + 11, 54);

  doc
    .fillColor(COLORS.textDark)
    .font("Helvetica-Bold")
    .fontSize(16)
    .text("Freedo", PAGE_MARGIN + 46, 50);

  doc
    .fillColor(COLORS.textGray)
    .font("Helvetica")
    .fontSize(9)
    .text("AI Freelancer Operating System", PAGE_MARGIN + 46, 70);

  // Document title, right-aligned
  doc
    .fillColor(COLORS.brand)
    .font("Helvetica-Bold")
    .fontSize(20)
    .text(documentTitle.toUpperCase(), PAGE_MARGIN, 52, {
      width: PAGE_WIDTH - PAGE_MARGIN * 2,
      align: "right",
    });

  doc
    .moveTo(PAGE_MARGIN, 96)
    .lineTo(PAGE_WIDTH - PAGE_MARGIN, 96)
    .strokeColor(COLORS.brand)
    .lineWidth(1.5)
    .stroke();

  return 112; // y-coordinate where the caller should continue drawing from
}

/**
 * Draws the footer + page number on the CURRENT page only. Call once per
 * page (see addFooterToAllPages for the multi-page case).
 */
function drawFooterOnCurrentPage(doc, pageNumber, totalPages) {
  const bottom = doc.page.height - 55;

  doc
    .moveTo(PAGE_MARGIN, bottom)
    .lineTo(PAGE_WIDTH - PAGE_MARGIN, bottom)
    .strokeColor(COLORS.border)
    .lineWidth(0.5)
    .stroke();

  doc
    .fillColor(COLORS.textLight)
    .font("Helvetica")
    .fontSize(8.5)
    .text("Generated by Freedo", PAGE_MARGIN, bottom + 10, { width: 250 });

  doc.text(`Page ${pageNumber} of ${totalPages}`, PAGE_MARGIN, bottom + 10, {
    width: PAGE_WIDTH - PAGE_MARGIN * 2,
    align: "right",
  });
}

/**
 * PDFKit only knows how many pages exist AFTER everything has been drawn
 * (since content can flow onto new pages automatically). So footers are
 * added in a final pass over doc.bufferedPageRange(), rather than while
 * content is being drawn — this is what correctly gives "Page 1 of 3"
 * instead of every page guessing wrong.
 */
function addFooterToAllPages(doc) {
  const range = doc.bufferedPageRange(); // { start, count }
  for (let i = 0; i < range.count; i++) {
    doc.switchToPage(range.start + i);
    drawFooterOnCurrentPage(doc, i + 1, range.count);
  }
}

function sectionHeading(doc, text, x, y) {
  doc.fillColor(COLORS.brand).font("Helvetica-Bold").fontSize(11).text(text.toUpperCase(), x, y);
  return y + 18;
}

function labelValue(doc, label, value, x, y, width = 240) {
  doc.fillColor(COLORS.textGray).font("Helvetica").fontSize(9).text(label, x, y);
  doc.fillColor(COLORS.textDark).font("Helvetica-Bold").fontSize(10).text(value || "-", x, y + 13, { width });
  return y + 34;
}

// ---------------------------------------------------------------------------
// INVOICE PDF
// ---------------------------------------------------------------------------

/**
 * `data` shape: { invoice, items, project, client }
 */
export function generateInvoicePDF(doc, data) {
  const { invoice, items = [], project, client } = data;

  let y = drawHeader(doc, "Invoice");

  // Invoice meta row: number/status on left, dates on right
  doc.fillColor(COLORS.textDark).font("Helvetica-Bold").fontSize(13).text(`# ${invoice.number}`, PAGE_MARGIN, y);

  const statusColor = { PAID: COLORS.success, PENDING: COLORS.warning, OVERDUE: COLORS.danger, DRAFT: COLORS.textGray };
  doc
    .fillColor(statusColor[invoice.status] || COLORS.textGray)
    .font("Helvetica-Bold")
    .fontSize(9)
    .text(invoice.status, PAGE_MARGIN, y + 18);

  doc.fillColor(COLORS.textGray).font("Helvetica").fontSize(9);
  doc.text(`Issue Date: ${formatDate(invoice.issueDate)}`, 350, y, { width: 195, align: "right" });
  doc.text(`Due Date: ${formatDate(invoice.dueDate)}`, 350, y + 14, { width: 195, align: "right" });
  y += 50;

  // Bill To / Project — two columns
  const colStartY = y;
  y = sectionHeading(doc, "Bill To", PAGE_MARGIN, y);
  doc.fillColor(COLORS.textDark).font("Helvetica-Bold").fontSize(10).text(client?.name || "-", PAGE_MARGIN, y);
  doc.fillColor(COLORS.textGray).font("Helvetica").fontSize(9).text(client?.email || "-", PAGE_MARGIN, y + 14);

  let y2 = sectionHeading(doc, "Project", 320, colStartY);
  doc.fillColor(COLORS.textDark).font("Helvetica-Bold").fontSize(10).text(project?.title || "-", 320, y2, { width: 225 });

  y += 45;

  // Items table
  const tableX = { item: PAGE_MARGIN, desc: 190, qty: 350, rate: 400, amount: 470 };
  doc.rect(PAGE_MARGIN, y, PAGE_WIDTH - PAGE_MARGIN * 2, 22).fill(COLORS.tableHeaderBg);
  doc.fillColor(COLORS.brandDark).font("Helvetica-Bold").fontSize(8.5);
  doc.text("ITEM", tableX.item + 8, y + 7);
  doc.text("DESCRIPTION", tableX.desc, y + 7);
  doc.text("QTY", tableX.qty, y + 7);
  doc.text("RATE", tableX.rate, y + 7);
  doc.text("AMOUNT", tableX.amount, y + 7);
  y += 22;

  let subtotal = 0;
  items.forEach((item, i) => {
    const qty = Number(item.qty);
    const rate = Number(item.rate);
    const amount = qty * rate;
    subtotal += amount;

    const rowHeight = 22;
    if (i % 2 === 1) doc.rect(PAGE_MARGIN, y, PAGE_WIDTH - PAGE_MARGIN * 2, rowHeight).fill("#FAFAFA");

    doc.fillColor(COLORS.textDark).font("Helvetica").fontSize(9);
    doc.text(item.name, tableX.item + 8, y + 6, { width: 130 });
    doc.fillColor(COLORS.textGray).text(item.description || "-", tableX.desc, y + 6, { width: 150 });
    doc.fillColor(COLORS.textDark).text(String(qty), tableX.qty, y + 6);
    doc.text(formatCurrency(rate), tableX.rate, y + 6);
    doc.font("Helvetica-Bold").text(formatCurrency(amount), tableX.amount, y + 6);

    y += rowHeight;

    // Manual page break if we're running out of room for the next row
    if (y > doc.page.height - 220) {
      doc.addPage();
      y = drawHeader(doc, "Invoice");
    }
  });

  y += 10;
  doc.moveTo(PAGE_MARGIN, y).lineTo(PAGE_WIDTH - PAGE_MARGIN, y).strokeColor(COLORS.border).stroke();
  y += 14;

  // Summary block, right-aligned
  const taxAmount = (subtotal * Number(invoice.taxRate)) / 100;
  const grandTotal = subtotal + taxAmount;
  const balanceDue = Math.max(0, grandTotal - Number(invoice.amountPaid));

  function summaryRow(label, value, bold = false, color = COLORS.textDark) {
    doc.fillColor(COLORS.textGray).font("Helvetica").fontSize(9.5).text(label, 350, y, { width: 100 });
    doc
      .fillColor(color)
      .font(bold ? "Helvetica-Bold" : "Helvetica")
      .fontSize(bold ? 11 : 9.5)
      .text(value, 450, y, { width: 95, align: "right" });
    y += 18;
  }

  summaryRow("Subtotal", formatCurrency(subtotal));
  summaryRow(`Tax (${invoice.taxRate}%)`, formatCurrency(taxAmount));
  summaryRow("Grand Total", formatCurrency(grandTotal), true);
  summaryRow("Amount Paid", formatCurrency(invoice.amountPaid));
  summaryRow("Balance Due", formatCurrency(balanceDue), true, COLORS.danger);
  y += 15;

  if (invoice.notes) {
    y = sectionHeading(doc, "Payment Notes", PAGE_MARGIN, y);
    doc.fillColor(COLORS.textDark).font("Helvetica").fontSize(9).text(invoice.notes, PAGE_MARGIN, y, { width: 495 });
  }
}

// ---------------------------------------------------------------------------
// PROPOSAL PDF
// ---------------------------------------------------------------------------

/**
 * `data` shape: { proposal, project, client }
 * `proposal.deliverables` and `proposal.technologies` are string arrays.
 */
export function generateProposalPDF(doc, data) {
  const { proposal, project, client } = data;

  let y = drawHeader(doc, "Proposal");

  doc.fillColor(COLORS.textDark).font("Helvetica-Bold").fontSize(14).text(project?.title || "Project Proposal", PAGE_MARGIN, y);
  y += 25;

  y = labelValue(doc, "PREPARED FOR", client?.name || "-", PAGE_MARGIN, y, 240);
  y -= 34;
  labelValue(doc, "STATUS", proposal.status, 350, y, 195);
  y += 34;

  y = sectionHeading(doc, "Introduction", PAGE_MARGIN, y);
  doc
    .fillColor(COLORS.textDark)
    .font("Helvetica")
    .fontSize(9.5)
    .text(
      proposal.overview ||
        `We're excited to present this proposal for ${project?.title || "your project"}, outlining our approach, deliverables, and timeline.`,
      PAGE_MARGIN,
      y,
      { width: 495 }
    );
  y = doc.y + 16;

  y = sectionHeading(doc, "Project Overview", PAGE_MARGIN, y);
  doc.fillColor(COLORS.textDark).font("Helvetica").fontSize(9.5).text(proposal.scope || "-", PAGE_MARGIN, y, { width: 495 });
  y = doc.y + 16;

  y = sectionHeading(doc, "Objectives", PAGE_MARGIN, y);
  doc.fillColor(COLORS.textDark).font("Helvetica").fontSize(9.5).text(proposal.objectives || "-", PAGE_MARGIN, y, { width: 495 });
  y = doc.y + 16;

  y = sectionHeading(doc, "Deliverables", PAGE_MARGIN, y);
  (proposal.deliverables || []).forEach((item) => {
    doc.fillColor(COLORS.textDark).font("Helvetica").fontSize(9.5).text(`•  ${item}`, PAGE_MARGIN + 5, y);
    y += 15;
  });
  y += 8;

  const colY = y;
  y = sectionHeading(doc, "Timeline", PAGE_MARGIN, y);
  doc.fillColor(COLORS.textDark).font("Helvetica-Bold").fontSize(10).text(`${proposal.timelineWeeks} weeks`, PAGE_MARGIN, y);

  let y3 = sectionHeading(doc, "Pricing", 320, colY);
  doc.fillColor(COLORS.textDark).font("Helvetica-Bold").fontSize(10).text(formatCurrency(proposal.budget), 320, y3);
  y += 40;

  // Acceptance section
  if (y > doc.page.height - 180) {
    doc.addPage();
    y = drawHeader(doc, "Proposal");
  }
  y = sectionHeading(doc, "Acceptance", PAGE_MARGIN, y);
  doc
    .fillColor(COLORS.textGray)
    .font("Helvetica")
    .fontSize(9)
    .text("By signing below, both parties agree to the terms outlined in this proposal.", PAGE_MARGIN, y, { width: 495 });
  y += 40;

  doc.moveTo(PAGE_MARGIN, y).lineTo(PAGE_MARGIN + 200, y).strokeColor(COLORS.border).stroke();
  doc.moveTo(320, y).lineTo(320 + 200, y).strokeColor(COLORS.border).stroke();
  doc.fillColor(COLORS.textGray).fontSize(8.5).text("Client Signature", PAGE_MARGIN, y + 5);
  doc.text("Freelancer Signature", 320, y + 5);
}

// ---------------------------------------------------------------------------
// CONTRACT PDF
// ---------------------------------------------------------------------------

/**
 * `data` shape: { contract, project, client, freelancer }
 * `contract` fields are treated loosely (contract.terms, .scope,
 * .paymentTerms, .ownership, .termination) since the exact Contract model
 * shape isn't confirmed yet — pass whatever text fields you have; anything
 * missing falls back to a sensible default paragraph so the PDF never
 * breaks on an undefined field.
 */
export function generateContractPDF(doc, data) {
  const { contract = {}, project, client, freelancer } = data;

  let y = drawHeader(doc, "Service Agreement");

  doc
    .fillColor(COLORS.textDark)
    .font("Helvetica-Bold")
    .fontSize(13)
    .text(`Agreement for: ${project?.title || "-"}`, PAGE_MARGIN, y, { width: 495 });
  y += 30;

  const colY = y;
  y = sectionHeading(doc, "Client", PAGE_MARGIN, y);
  doc.fillColor(COLORS.textDark).font("Helvetica-Bold").fontSize(10).text(client?.name || "-", PAGE_MARGIN, y);
  doc.fillColor(COLORS.textGray).font("Helvetica").fontSize(9).text(client?.email || "-", PAGE_MARGIN, y + 14);

  let y2 = sectionHeading(doc, "Freelancer", 320, colY);
  doc.fillColor(COLORS.textDark).font("Helvetica-Bold").fontSize(10).text(freelancer?.name || "Freedo User", 320, y2);
  doc.fillColor(COLORS.textGray).font("Helvetica").fontSize(9).text(freelancer?.email || "-", 320, y2 + 14);
  y += 45;

  function textSection(title, content, fallback) {
    if (y > doc.page.height - 160) {
      doc.addPage();
      y = drawHeader(doc, "Service Agreement");
    }
    y = sectionHeading(doc, title, PAGE_MARGIN, y);
    doc.fillColor(COLORS.textDark).font("Helvetica").fontSize(9.5).text(content || fallback, PAGE_MARGIN, y, { width: 495 });
    y = doc.y + 16;
  }

  textSection("Scope of Work", contract.scope, `This agreement covers all work related to "${project?.title || "the project"}" as outlined between both parties.`);
  textSection("Terms", contract.terms, "Standard terms apply as agreed upon by both parties prior to project commencement.");
  textSection("Payment Terms", contract.paymentTerms, "Payment is due per the agreed invoicing schedule, within the terms specified on each invoice.");
  textSection("Ownership", contract.ownership, "Upon full payment, all final deliverables become the property of the client.");
  textSection("Termination", contract.termination, "Either party may terminate this agreement with written notice, subject to payment for work completed to date.");

  // Signature blocks
  if (y > doc.page.height - 140) {
    doc.addPage();
    y = drawHeader(doc, "Service Agreement");
  }
  y += 20;
  doc.moveTo(PAGE_MARGIN, y).lineTo(PAGE_MARGIN + 200, y).strokeColor(COLORS.border).stroke();
  doc.moveTo(320, y).lineTo(320 + 200, y).strokeColor(COLORS.border).stroke();
  doc.fillColor(COLORS.textGray).fontSize(8.5).text("Client Signature & Date", PAGE_MARGIN, y + 5);
  doc.text("Freelancer Signature & Date", 320, y + 5);
}

// ---------------------------------------------------------------------------
// Public entry point used by the controller — wraps drawing + footer pass +
// buffer collection in one place, so the controller doesn't repeat this
// boilerplate for all three document types.
// ---------------------------------------------------------------------------

/**
 * `type`: "invoice" | "proposal" | "contract"
 * Returns a Promise<Buffer> of the finished PDF.
 */
export function renderPdfToBuffer(type, data) {
  const drawFn = { invoice: generateInvoicePDF, proposal: generateProposalPDF, contract: generateContractPDF }[type];
  if (!drawFn) throw new Error(`Unknown PDF type: ${type}`);

  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: "A4", margin: PAGE_MARGIN, bufferPages: true });
    const chunks = [];

    doc.on("data", (chunk) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    drawFn(doc, data);
    addFooterToAllPages(doc); // must run before doc.end() while pages are still buffered
    doc.end();
  });
}