import { useEffect } from "react";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { z } from "zod";

import Modal from "../common/Modal";
import Input from "../common/Input";
import Button from "../common/Button";

/*
|--------------------------------------------------------------------------
| InvoiceModal
|--------------------------------------------------------------------------
|
| Same one-component-two-modes pattern as ClientModal/ProjectModal.
|
| Note: invoiceNumber is NOT a form field — it's generated by the backend
| when an invoice is created (e.g. "INV-2026-0042"), same reasoning as
| documents not having a create() form: some things shouldn't be
| freely typed by the user. In edit mode, the existing invoice number is
| shown as read-only text in the header area instead of an input.
|
| status here only offers "draft" and "sent" — NOT "paid" or "overdue".
| Paid is set via the separate markAsPaid() action on InvoiceTable/
| Invoices.jsx (a deliberate one-way action, not something you undo by
| editing a dropdown), and overdue is something the backend should
| compute from dueDate vs today, not something a user manually picks.
|
| Props:
|   isOpen, onClose, onSubmit, isSaving — same as ClientModal
|   invoice   — optional; present = edit mode
|   projects  — array of { id, name, clientName } for the project dropdown
|
*/

const invoiceSchema = z.object({
    projectId: z.string().min(1, "Please select a project"),
    amount: z.coerce
        .number({ invalid_type_error: "Amount must be a number" })
        .positive("Amount must be greater than 0"),
    dueDate: z.string().min(1, "Due date is required"),
    status: z.enum(["draft", "sent"]),
    notes: z.string().optional(),
});

export default function InvoiceModal({
    isOpen,
    onClose,
    onSubmit,
    invoice,
    projects = [],
    isSaving = false,
}) {
    const isEditMode = Boolean(invoice);

    const {
        register,
        handleSubmit,
        reset,
        formState: { errors },
    } = useForm({
        resolver: zodResolver(invoiceSchema),
        defaultValues: {
            projectId: "",
            amount: "",
            dueDate: "",
            status: "draft",
            notes: "",
        },
    });

    useEffect(() => {
        if (isOpen) {
            reset(
                invoice
                    ? {
                        projectId: invoice.projectId ?? "",
                        amount: invoice.amount ?? "",
                        dueDate: invoice.dueDate ? invoice.dueDate.slice(0, 10) : "",
                        status:
                            invoice.status === "paid" || invoice.status === "overdue"
                                ? "sent" // fall back to a valid form option; the real
                                // status stays untouched unless the user submits
                                : invoice.status ?? "draft",
                        notes: invoice.notes ?? "",
                    }
                    : { projectId: "", amount: "", dueDate: "", status: "draft", notes: "" }
            );
        }
    }, [isOpen, invoice, reset]);

    function handleFormSubmit(data) {
        onSubmit(data);
    }

    return (
        <Modal
            isOpen={isOpen}
            onClose={onClose}
            title={isEditMode ? "Edit Invoice" : "Create Invoice"}
        >
            {isEditMode && (
                <p className="mb-4 text-sm text-slate-500">
                    Invoice number:{" "}
                    <span className="font-medium text-slate-800">{invoice.invoiceNumber}</span>
                </p>
            )}

            <form onSubmit={handleSubmit(handleFormSubmit)} className="flex flex-col gap-4">
                <div className="space-y-1.5">
                    <label htmlFor="projectId" className="block text-sm font-medium text-slate-700 dark:text-slate-300">
                        Project<span className="ml-1 text-red-500">*</span>
                    </label>
                    <select
                        id="projectId"
                        {...register("projectId")}
                        className={[
                            "w-full rounded-lg border px-3 py-2 text-sm transition-all duration-200",
                            "focus:outline-none focus:ring-2 focus:ring-offset-0",
                            errors.projectId
                                ? "border-red-300 focus:border-red-500 focus:ring-red-500"
                                : "border-slate-300 dark:border-slate-600 focus:border-purple-500 focus:ring-purple-500",
                        ].join(" ")}
                    >
                        <option value="">Select a project...</option>
                        {projects.map((project) => (
                            <option key={project.id} value={project.id}>
                                {project.name} — {project.clientName}
                            </option>
                        ))}
                    </select>
                    {errors.projectId && (
                        <p className="text-sm text-red-600">{errors.projectId.message}</p>
                    )}
                </div>

                <Input
                    label="Amount (₹)"
                    required
                    type="number"
                    placeholder="45000"
                    {...register("amount")}
                    error={errors.amount?.message}
                />

                <Input
                    label="Due date"
                    required
                    type="date"
                    {...register("dueDate")}
                    error={errors.dueDate?.message}
                />

                <div className="space-y-1.5">
                    <label htmlFor="status" className="block text-sm font-medium text-slate-700 dark:text-slate-300">
                        Status
                    </label>
                    <select
                        id="status"
                        {...register("status")}
                        className="w-full rounded-lg border border-slate-300 px-3 py-2 text-sm transition-all duration-200 focus:border-purple-500 focus:outline-none focus:ring-2 focus:ring-purple-500 dark:border-slate-700 dark:bg-slate-800 dark:text-slate-100"
                    >
                        <option value="draft">Draft</option>
                        <option value="sent">Sent</option>
                    </select>
                    <p className="text-xs text-slate-400">
                        "Paid" is set from the invoice list, not here.
                    </p>
                </div>

                <div className="space-y-1.5">
                    <label htmlFor="notes" className="block text-sm font-medium text-slate-700 dark:text-slate-300">
                        Notes (optional)
                    </label>
                    <textarea
                        id="notes"
                        rows={3}
                        {...register("notes")}
                        placeholder="Payment terms, thank-you note, etc."
                        className="w-full rounded-lg border border-slate-300 px-3 py-2 text-sm transition-all duration-200 focus:border-purple-500 focus:outline-none focus:ring-2 focus:ring-purple-500 dark:border-slate-700 dark:bg-slate-800 dark:text-slate-100"
                    />
                </div>

                <div className="mt-2 flex justify-end gap-2">
                    <Button type="button" variant="outline" onClick={onClose}>
                        Cancel
                    </Button>
                    <Button type="submit" isLoading={isSaving}>
                        {isEditMode ? "Save Changes" : "Create Invoice"}
                    </Button>
                </div>
            </form>
        </Modal>
    );
}